### ISSUE TITLE
동적 nfc vs nfc(모드중 read&write모드)

### ISSUE THREAD

**Issue by yandusty** [Mr21percent/osproject#1]
두개가 뭔차이인지..

**Comment by Mr21percent** [comment]
nfc read&write는 우리가 일반적으로 아는 카드에 있는 정보를 받아들이고 기록 할 수 있는 장치로 보입니다
이와 달리 동적 nfc는 저장된 단말에 존재하는 정보를 바꿔가면서 read장치에 인식시킬수 있는것으로 보입니다
